// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkqmhfvllsuktaznfdda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrcW1oZnZsbHN1a3Rhem5mZGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjU3MDUsImV4cCI6MjA3MDAwMTcwNX0.Tkg6R8VzPTu6MCOyds0NzS3wi85goOcFPNs6ulfUogY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});